TRouteHandler = RouteHandlerImpl.TRouteHandler;

TRouterFactory = RouterFactoryImpl.TRouterFactory;
TSimpleRouterFactory = SimpleRouterFactoryImpl.TSimpleRouterFactory;
TCombineRouterFactory = CombineRouterFactoryImpl.TCombineRouterFactory;
TRegexRouterFactory = RegexRouterFactoryImpl.TRegexRouterFactory;

TRouteBuilder = RouteBuilderImpl.TRouteBuilder;
TCompositeRouteBuilder = CompositeRouteBuilderImpl.TCompositeRouteBuilder;
